project:
  type: website

website:
  title: "Oscar Quintero"
  navbar:
    background: dark
    search: true
    left:
      - text: About
        href: about.qmd
      - text: Projects
        href: Projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
  sidebar:
    collapse: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto